### Basics

Built on top of numpy. Therefore ,
<br>
* most mathematical and scientific functions are available.

#### Operations in sci py

* File input/output
<hr>
* numercal operations - scipy.integrate
<br>
* special functions - scipy.special
<br>
* linear algebra operations - scipy.linalg
<br>
* statistics and random numbers - scipy.stats
<hr>
* Signal processing - scipy.signal
<br>
* fast fourier transform - scipy.fftpack
<hr>
* interpolaiton - scipy.interpolate
<br>
* ooptimization - scipy.optimize
<br>
* scipy spatial - scipy.spatial
<hr>
* image manipulation - scipy.ndimage

### 1) File IO - SciPy

In [2]:
# importing libraries

import scipy
import numpy as np

In [3]:
# making  numpy array

demo = np.arange(1,10,1)
scipy.io.savemat('file.mat' , {'test' : demo} )

AttributeError: module 'scipy' has no attribute 'io'

In [ ]:
scipy.io.loadmat('file.mat')

### 2) Mathematical operations

In [4]:
print("Permutations and combinations")
print("\nP(5,2) = " , scipy.special.perm(5,2))
print("P(10,2) = " , scipy.special.perm(10,2))
print("\nC(6,1) = " , scipy.special.comb(6,1))
print("C(8,2) = " , scipy.special.comb(8,2))

Permutations and combinations

P(5,2) =  20.0
P(10,2) =  90.0

C(6,1) =  6.0
C(8,2) =  28.0


In [5]:
print("Linear Algebra Operations \n")
print("Solve \n\tx + y = 2\n\t2x - y = 4")

x = np.array([[1,1],[2,-1]])
y = np.array([
    [2],
    [4]
])

print("On solving,\nx =" , scipy.linalg.solve(x,y)[0][0])
print("y =" , scipy.linalg.solve(x,y)[1][0])

Linear Algebra Operations 

Solve 
	x + y = 2
	2x - y = 4
On solving,
x = 2.0
y = 0.0


In [6]:
print("Finding Determinant")

mat = np.array([
    [1,2,1],
    [2,
     1,1],
    [3,0,-3]
])

print("\nLet matrix A = \n" , mat , "\n")

print("The determinant value = " , scipy.linalg.det(mat))

Finding Determinant

Let matrix A = 
 [[ 1  2  1]
 [ 2  1  1]
 [ 3  0 -3]] 

The determinant value =  12.0


In [7]:
print("Finding the inverse of a matrix (say matrix A)\n")

print("inv(A) = \n" , scipy.linalg.inv(mat))

Finding the inverse of a matrix (say matrix A)

inv(A) = 
 [[-0.25        0.5         0.08333333]
 [ 0.75       -0.5         0.08333333]
 [-0.25        0.5        -0.25      ]]


In [8]:
from scipy import integrate

In [9]:
print("Performing Integration\n")

print("Let the function be y = x**2 + 3*x")
f = lambda x : x**2 + 3*x

print("\nIntegrating y between 0 to 5 limits , ")
print(integrate.quad(f , 0 , 2)[0])

Performing Integration

Let the function be y = x**2 + 3*x

Integrating y between 0 to 5 limits , 
8.666666666666668


### 3) Optimization

In [10]:
import scipy.optimize as optimize
